### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sovtec** [XZot1K/PhysicsToGo#16]
When enabling in a world that has been modified it brings back the original world, it does not save, would be nice for it to save the correct state of that world to be regenerated

Would be nice to get some support at your discord also

**Comment by XZot1K** [comment]
> When enabling in a world that has been modified it brings back the original world, it does not save, would be nice for it to save the correct state of that world to be regenerated
> 
> Would be nice to get some support at your discord also

I'm pretty sure this is identical to what was just fixed in 2.0.7. If not, let me know and I will look further!
