### ISSUE TITLE
Double chests' contents are not restored

### ISSUE THREAD

**Issue by timmyRS** [XZot1K/PhysicsToGo#3]
I'm using Spigot 1.13.2 and double chests' contents are not restored.

**Comment by timmyRS** [comment]
You should close the issues here on Github after you fixed them, but thanks for fixing the problem anyway.

**Comment by NanashiTheNameless** [comment]
im still getting this issue, can you send your config and plugin version?
im on paper 1.19.4
(using PTG 2.0.6)
